// scripts/seed-foods.ts
// Run with: npx tsx scripts/seed-foods.ts
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { MongoClient } from "mongodb";

const MONGODB_URI = process.env.MONGODB_URI!;
const DB_NAME = "fitup";
const FOOD_COLLECTION = "food";

// Clean names, highly accurate USDA macros per 100g
const foodData = [
  // --- GRAINS & STARCHES ---
  {
    name: "White Rice",
    localized: "Biela ryža",
    calories_per_100g: 360,
    protein: 7.0,
    carbohydrates: 80.0,
    sugar: 0.1,
    fat: 0.6,
    fiber: 1.3,
    salt: 0.01,
  },
  {
    name: "Brown Rice",
    localized: "Hnedá ryža",
    calories_per_100g: 367,
    protein: 7.5,
    carbohydrates: 76.0,
    sugar: 0.6,
    fat: 2.8,
    fiber: 3.4,
    salt: 0.01,
  },
  {
    name: "Oats",
    localized: "Ovsené vločky",
    calories_per_100g: 379,
    protein: 13.0,
    carbohydrates: 68.0,
    sugar: 1.0,
    fat: 6.5,
    fiber: 10.0,
    salt: 0.01,
  },
  {
    name: "Quinoa",
    localized: "Quinoa",
    calories_per_100g: 368,
    protein: 14.0,
    carbohydrates: 64.0,
    sugar: 0.0,
    fat: 6.0,
    fiber: 7.0,
    salt: 0.01,
  },
  {
    name: "Pasta",
    localized: "Cestoviny",
    calories_per_100g: 350,
    protein: 12.0,
    carbohydrates: 71.0,
    sugar: 3.0,
    fat: 1.5,
    fiber: 3.0,
    salt: 0.02,
  },
  {
    name: "Potatoes",
    localized: "Zemiaky",
    calories_per_100g: 77,
    protein: 2.0,
    carbohydrates: 17.0,
    sugar: 0.8,
    fat: 0.1,
    fiber: 2.2,
    salt: 0.01,
  },
  {
    name: "Sweet Potatoes",
    localized: "Batáty",
    calories_per_100g: 86,
    protein: 1.6,
    carbohydrates: 20.0,
    sugar: 4.2,
    fat: 0.1,
    fiber: 3.0,
    salt: 0.14,
  },
  {
    name: "Bread",
    localized: "Chlieb",
    calories_per_100g: 265,
    protein: 9.0,
    carbohydrates: 49.0,
    sugar: 5.0,
    fat: 3.2,
    fiber: 2.7,
    salt: 1.1,
  },
  {
    name: "Jasmine Rice",
    localized: "Jazmínová ryža",
    calories_per_100g: 356,
    protein: 7.0,
    carbohydrates: 80.0,
    sugar: 0.1,
    fat: 0.8,
    fiber: 1.3,
    salt: 0.0,
  },
  {
    name: "Basmati Rice",
    localized: "Basmati ryža",
    calories_per_100g: 356,
    protein: 7.0,
    carbohydrates: 78.0,
    sugar: 0.1,
    fat: 0.8,
    fiber: 1.3,
    salt: 0.0,
  },
  {
    name: "Couscous",
    localized: "Kuskus",
    calories_per_100g: 356,
    protein: 12.8,
    carbohydrates: 72.4,
    sugar: 1.7,
    fat: 0.6,
    fiber: 5.0,
    salt: 0.01,
  },
  {
    name: "Bulgur",
    localized: "Bulgur",
    calories_per_100g: 342,
    protein: 12.3,
    carbohydrates: 76.0,
    sugar: 0.8,
    fat: 1.3,
    fiber: 12.5,
    salt: 0.02,
  },
  {
    name: "Buckwheat",
    localized: "Pohánka",
    calories_per_100g: 343,
    protein: 13.3,
    carbohydrates: 71.5,
    sugar: 0.0,
    fat: 3.4,
    fiber: 10.0,
    salt: 0.01,
  },
  {
    name: "White Bread",
    localized: "Biely chlieb",
    calories_per_100g: 265,
    protein: 9.0,
    carbohydrates: 49.0,
    sugar: 5.0,
    fat: 3.2,
    fiber: 2.7,
    salt: 1.1,
  },
  {
    name: "Whole Wheat Bread",
    localized: "Celozrnný chlieb",
    calories_per_100g: 247,
    protein: 13.0,
    carbohydrates: 41.0,
    sugar: 6.0,
    fat: 3.4,
    fiber: 7.0,
    salt: 1.0,
  },
  {
    name: "Tortilla",
    localized: "Pšeničná tortilla",
    calories_per_100g: 297,
    protein: 8.0,
    carbohydrates: 50.0,
    sugar: 2.0,
    fat: 8.0,
    fiber: 3.0,
    salt: 1.5,
  },
  {
    name: "Rye Bread",
    localized: "Ražný chlieb",
    calories_per_100g: 259,
    protein: 8.5,
    carbohydrates: 48.0,
    sugar: 3.9,
    fat: 3.3,
    fiber: 5.8,
    salt: 1.7,
  },
  {
    name: "Rice Cakes",
    localized: "Ryžové chlebíky",
    calories_per_100g: 387,
    protein: 8.2,
    carbohydrates: 81.5,
    sugar: 0.8,
    fat: 2.8,
    fiber: 4.1,
    salt: 0.3,
  },
  {
    name: "Corn Tortilla",
    localized: "Kukuričná tortilla",
    calories_per_100g: 218,
    protein: 5.7,
    carbohydrates: 45.0,
    sugar: 0.9,
    fat: 2.8,
    fiber: 6.3,
    salt: 0.1,
  },
  {
    name: "Jasmine Rice (cooked)",
    localized: "Jazmínová ryža (varená)",
    calories_per_100g: 129,
    protein: 2.7,
    carbohydrates: 28.0,
    sugar: 0.1,
    fat: 0.3,
    fiber: 0.4,
    salt: 0.0,
  },
  {
    name: "White Rice (cooked)",
    localized: "Biela ryža (varená)",
    calories_per_100g: 130,
    protein: 2.7,
    carbohydrates: 28.0,
    sugar: 0.1,
    fat: 0.3,
    fiber: 0.4,
    salt: 0.0,
  },
  {
    name: "Brown Rice (cooked)",
    localized: "Hnedá ryža (varená)",
    calories_per_100g: 111,
    protein: 2.6,
    carbohydrates: 23.0,
    sugar: 0.4,
    fat: 0.9,
    fiber: 1.8,
    salt: 0.0,
  },
  {
    name: "Potatoes (boiled)",
    localized: "Zemiaky (varené)",
    calories_per_100g: 87,
    protein: 1.9,
    carbohydrates: 20.0,
    sugar: 0.9,
    fat: 0.1,
    fiber: 1.8,
    salt: 0.0,
  },
  {
    name: "Sweet Potatoes (boiled)",
    localized: "Batáty (varené)",
    calories_per_100g: 76,
    protein: 1.4,
    carbohydrates: 18.0,
    sugar: 5.7,
    fat: 0.1,
    fiber: 2.5,
    salt: 0.08,
  },

  // --- PROTEINS (MEAT & EGGS) ---
  {
    name: "Chicken Breast",
    localized: "Kuracie prsia",
    calories_per_100g: 120,
    protein: 22.5,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 2.6,
    fiber: 0.0,
    salt: 0.11,
  },
  {
    name: "Chicken Thighs",
    localized: "Kuracie stehná",
    calories_per_100g: 177,
    protein: 17.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 12.0,
    fiber: 0.0,
    salt: 0.2,
  },
  {
    name: "Beef Minced",
    localized: "Hovädzie mleté",
    calories_per_100g: 250,
    protein: 26.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 15.0,
    fiber: 0.0,
    salt: 0.18,
  },
  {
    name: "Pork Loin",
    localized: "Bravčové karé",
    calories_per_100g: 143,
    protein: 21.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 6.0,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Salmon",
    localized: "Losos",
    calories_per_100g: 208,
    protein: 20.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 13.0,
    fiber: 0.0,
    salt: 0.11,
  },
  {
    name: "Tuna",
    localized: "Tuniak",
    calories_per_100g: 130,
    protein: 28.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 1.0,
    fiber: 0.0,
    salt: 0.8,
  },
  {
    name: "Eggs",
    localized: "Vajcia",
    calories_per_100g: 143,
    protein: 12.6,
    carbohydrates: 0.7,
    sugar: 0.2,
    fat: 9.5,
    fiber: 0.0,
    salt: 0.35,
  },
  {
    name: "Egg Whites",
    localized: "Vaječné bielka",
    calories_per_100g: 52,
    protein: 11.0,
    carbohydrates: 0.7,
    sugar: 0.7,
    fat: 0.2,
    fiber: 0.0,
    salt: 0.4,
  },
  {
    name: "Turkey Breast",
    localized: "Morčacie prsia",
    calories_per_100g: 135,
    protein: 30.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 1.0,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Pork Minced",
    localized: "Bravčové mleté",
    calories_per_100g: 263,
    protein: 17.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 21.0,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Pork Shoulder",
    localized: "Bravčové plece",
    calories_per_100g: 186,
    protein: 20.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 12.0,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Beef Ribeye",
    localized: "Hovädzí steak (Ribeye)",
    calories_per_100g: 291,
    protein: 24.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 22.0,
    fiber: 0.0,
    salt: 0.15,
  },
  {
    name: "Cod Fish",
    localized: "Treska",
    calories_per_100g: 82,
    protein: 18.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 0.7,
    fiber: 0.0,
    salt: 0.2,
  },
  {
    name: "Tofu",
    localized: "Tofu",
    calories_per_100g: 144,
    protein: 17.0,
    carbohydrates: 3.0,
    sugar: 0.5,
    fat: 9.0,
    fiber: 2.3,
    salt: 0.02,
  },
  {
    name: "Tempeh",
    localized: "Tempeh",
    calories_per_100g: 193,
    protein: 19.0,
    carbohydrates: 9.0,
    sugar: 0.0,
    fat: 11.0,
    fiber: 3.8,
    salt: 0.02,
  },
  {
    name: "Red Lentils",
    localized: "Červená šošovica",
    calories_per_100g: 353,
    protein: 25.0,
    carbohydrates: 60.0,
    sugar: 2.0,
    fat: 1.1,
    fiber: 10.0,
    salt: 0.01,
  },
  {
    name: "Canned Chickpeas",
    localized: "Cícer z konzervy",
    calories_per_100g: 139,
    protein: 7.0,
    carbohydrates: 20.0,
    sugar: 0.0,
    fat: 2.5,
    fiber: 6.0,
    salt: 0.3,
  },
  {
    name: "Canned Black Beans",
    localized: "Čierna fazuľa z konzervy",
    calories_per_100g: 114,
    protein: 7.6,
    carbohydrates: 16.0,
    sugar: 0.0,
    fat: 0.5,
    fiber: 5.5,
    salt: 0.3,
  },
  {
    name: "Shrimp",
    localized: "Krevety (varené)",
    calories_per_100g: 99,
    protein: 24.0,
    carbohydrates: 0.2,
    sugar: 0.0,
    fat: 0.3,
    fiber: 0.0,
    salt: 0.57,
  },
  {
    name: "Canned Tuna (in water)",
    localized: "Tuniak vo vlastnej šťave",
    calories_per_100g: 116,
    protein: 26.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 1.0,
    fiber: 0.0,
    salt: 0.8,
  },
  {
    name: "Ham",
    localized: "Šunka",
    calories_per_100g: 110,
    protein: 17.0,
    carbohydrates: 1.5,
    sugar: 1.0,
    fat: 4.0,
    fiber: 0.0,
    salt: 2.0,
  },
  {
    name: "White Beans",
    localized: "Biela fazuľa",
    calories_per_100g: 139,
    protein: 9.7,
    carbohydrates: 25.0,
    sugar: 0.4,
    fat: 0.4,
    fiber: 6.3,
    salt: 0.01,
  },
  {
    name: "Chicken Breast (cooked)",
    localized: "Kuracie prsia (varené)",
    calories_per_100g: 165,
    protein: 31.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 3.6,
    fiber: 0.0,
    salt: 0.07,
  },
  {
    name: "Beef Sirloin",
    localized: "Hovädzia sviečková (Sirloin)",
    calories_per_100g: 244,
    protein: 27.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 15.0,
    fiber: 0.0,
    salt: 0.06,
  },
  {
    name: "Turkey Ham",
    localized: "Morčacia šunka",
    calories_per_100g: 104,
    protein: 17.0,
    carbohydrates: 2.0,
    sugar: 1.0,
    fat: 3.0,
    fiber: 0.0,
    salt: 2.1,
  },
  {
    name: "Trout",
    localized: "Pstruh",
    calories_per_100g: 148,
    protein: 21.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 6.6,
    fiber: 0.0,
    salt: 0.05,
  },

  // --- DAIRY & ALTERNATIVES ---
  {
    name: "Milk",
    localized: "Mlieko",
    calories_per_100g: 47,
    protein: 3.4,
    carbohydrates: 4.9,
    sugar: 4.9,
    fat: 1.5,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Greek Yogurt",
    localized: "Grécky jogurt",
    calories_per_100g: 59,
    protein: 10.0,
    carbohydrates: 3.6,
    sugar: 3.6,
    fat: 0.4,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Cottage Cheese",
    localized: "Cottage syr",
    calories_per_100g: 84,
    protein: 11.0,
    carbohydrates: 4.3,
    sugar: 2.7,
    fat: 2.3,
    fiber: 0.0,
    salt: 0.8,
  },
  {
    name: "Cheddar Cheese",
    localized: "Čedar",
    calories_per_100g: 402,
    protein: 25.0,
    carbohydrates: 1.3,
    sugar: 0.5,
    fat: 33.0,
    fiber: 0.0,
    salt: 1.8,
  },
  {
    name: "Mozzarella",
    localized: "Mozzarella",
    calories_per_100g: 300,
    protein: 22.0,
    carbohydrates: 2.2,
    sugar: 1.0,
    fat: 22.0,
    fiber: 0.0,
    salt: 1.5,
  },
  {
    name: "Butter",
    localized: "Maslo",
    calories_per_100g: 717,
    protein: 0.8,
    carbohydrates: 0.1,
    sugar: 0.1,
    fat: 81.0,
    fiber: 0.0,
    salt: 0.02,
  },
  {
    name: "Sour Cream (18%)",
    localized: "Kyslá smotana (18%)",
    calories_per_100g: 196,
    protein: 2.6,
    carbohydrates: 3.5,
    sugar: 3.5,
    fat: 18.0,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Skyr (Plain)",
    localized: "Skyr",
    calories_per_100g: 62,
    protein: 11.0,
    carbohydrates: 4.0,
    sugar: 4.0,
    fat: 0.2,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Parmesan Cheese",
    localized: "Parmezán",
    calories_per_100g: 431,
    protein: 38.0,
    carbohydrates: 4.1,
    sugar: 0.8,
    fat: 29.0,
    fiber: 0.0,
    salt: 1.8,
  },
  {
    name: "Feta Cheese",
    localized: "Feta syr",
    calories_per_100g: 264,
    protein: 14.0,
    carbohydrates: 4.0,
    sugar: 4.0,
    fat: 21.0,
    fiber: 0.0,
    salt: 2.8,
  },
  {
    name: "Ricotta",
    localized: "Ricotta",
    calories_per_100g: 174,
    protein: 11.0,
    carbohydrates: 3.0,
    sugar: 0.3,
    fat: 13.0,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Cream Cheese",
    localized: "Krémový syr",
    calories_per_100g: 342,
    protein: 6.0,
    carbohydrates: 4.0,
    sugar: 3.2,
    fat: 34.0,
    fiber: 0.0,
    salt: 0.8,
  },
  {
    name: "Whey Protein Powder",
    localized: "Srvátkový proteín",
    calories_per_100g: 390,
    protein: 80.0,
    carbohydrates: 6.0,
    sugar: 3.0,
    fat: 6.0,
    fiber: 0.0,
    salt: 0.4,
  },
  {
    name: "Soy Milk",
    localized: "Sójové mlieko",
    calories_per_100g: 43,
    protein: 3.3,
    carbohydrates: 4.0,
    sugar: 2.5,
    fat: 1.8,
    fiber: 0.6,
    salt: 0.1,
  },
  {
    name: "Almond Milk",
    localized: "Mandľové mlieko",
    calories_per_100g: 15,
    protein: 0.5,
    carbohydrates: 0.3,
    sugar: 0.0,
    fat: 1.1,
    fiber: 0.2,
    salt: 0.15,
  },
  {
    name: "Kefir (Plain)",
    localized: "Kefír",
    calories_per_100g: 61,
    protein: 3.5,
    carbohydrates: 4.0,
    sugar: 4.0,
    fat: 3.5,
    fiber: 0.0,
    salt: 0.1,
  },
  {
    name: "Gouda Cheese",
    localized: "Gouda",
    calories_per_100g: 356,
    protein: 25.0,
    carbohydrates: 2.2,
    sugar: 2.2,
    fat: 27.0,
    fiber: 0.0,
    salt: 2.0,
  },
  {
    name: "Goat Cheese",
    localized: "Kozí syr",
    calories_per_100g: 268,
    protein: 19.0,
    carbohydrates: 0.9,
    sugar: 0.9,
    fat: 21.0,
    fiber: 0.0,
    salt: 0.9,
  },
  {
    name: "Brie Cheese",
    localized: "Syr Brie",
    calories_per_100g: 334,
    protein: 21.0,
    carbohydrates: 0.5,
    sugar: 0.5,
    fat: 28.0,
    fiber: 0.0,
    salt: 1.6,
  },

  // --- VEGETABLES ---
  {
    name: "Broccoli",
    localized: "Brokolica",
    calories_per_100g: 34,
    protein: 2.8,
    carbohydrates: 6.6,
    sugar: 1.7,
    fat: 0.4,
    fiber: 2.6,
    salt: 0.08,
  },
  {
    name: "Spinach",
    localized: "Špenát",
    calories_per_100g: 23,
    protein: 2.9,
    carbohydrates: 3.6,
    sugar: 0.4,
    fat: 0.4,
    fiber: 2.2,
    salt: 0.2,
  },
  {
    name: "Carrots",
    localized: "Mrkva",
    calories_per_100g: 41,
    protein: 0.9,
    carbohydrates: 9.6,
    sugar: 4.7,
    fat: 0.2,
    fiber: 2.8,
    salt: 0.17,
  },
  {
    name: "Onion",
    localized: "Cibuľa",
    calories_per_100g: 40,
    protein: 1.1,
    carbohydrates: 9.3,
    sugar: 4.2,
    fat: 0.1,
    fiber: 1.7,
    salt: 0.01,
  },
  {
    name: "Garlic",
    localized: "Cesnak",
    calories_per_100g: 149,
    protein: 6.4,
    carbohydrates: 33.0,
    sugar: 1.0,
    fat: 0.5,
    fiber: 2.1,
    salt: 0.04,
  },
  {
    name: "Tomatoes",
    localized: "Paradajky",
    calories_per_100g: 18,
    protein: 0.9,
    carbohydrates: 3.9,
    sugar: 2.6,
    fat: 0.2,
    fiber: 1.2,
    salt: 0.01,
  },
  {
    name: "Bell Pepper",
    localized: "Paprika",
    calories_per_100g: 31,
    protein: 1.0,
    carbohydrates: 6.0,
    sugar: 4.2,
    fat: 0.3,
    fiber: 2.1,
    salt: 0.01,
  },
  {
    name: "Cucumber",
    localized: "Uhorka",
    calories_per_100g: 15,
    protein: 0.6,
    carbohydrates: 3.6,
    sugar: 1.7,
    fat: 0.1,
    fiber: 0.5,
    salt: 0.01,
  },
  {
    name: "Zucchini",
    localized: "Cuketa",
    calories_per_100g: 17,
    protein: 1.2,
    carbohydrates: 3.1,
    sugar: 2.5,
    fat: 0.3,
    fiber: 1.0,
    salt: 0.02,
  },
  {
    name: "Cauliflower",
    localized: "Karfiol",
    calories_per_100g: 25,
    protein: 1.9,
    carbohydrates: 5.0,
    sugar: 1.9,
    fat: 0.3,
    fiber: 2.0,
    salt: 0.08,
  },
  {
    name: "Cabbage",
    localized: "Kapusta",
    calories_per_100g: 25,
    protein: 1.3,
    carbohydrates: 6.0,
    sugar: 3.2,
    fat: 0.1,
    fiber: 2.5,
    salt: 0.05,
  },
  {
    name: "Mushrooms",
    localized: "Šampiňóny",
    calories_per_100g: 22,
    protein: 3.1,
    carbohydrates: 3.3,
    sugar: 2.0,
    fat: 0.3,
    fiber: 1.0,
    salt: 0.01,
  },
  {
    name: "Sweet Corn",
    localized: "Sladká kukurica",
    calories_per_100g: 86,
    protein: 3.2,
    carbohydrates: 19.0,
    sugar: 6.2,
    fat: 1.2,
    fiber: 2.0,
    salt: 0.04,
  },
  {
    name: "Green Peas",
    localized: "Hrášok",
    calories_per_100g: 81,
    protein: 5.4,
    carbohydrates: 14.0,
    sugar: 5.7,
    fat: 0.4,
    fiber: 5.1,
    salt: 0.01,
  },
  {
    name: "Pumpkin",
    localized: "Tekvica",
    calories_per_100g: 26,
    protein: 1.0,
    carbohydrates: 6.5,
    sugar: 2.8,
    fat: 0.1,
    fiber: 0.5,
    salt: 0.0,
  },

  // --- FRUITS ---
  {
    name: "Banana",
    localized: "Banán",
    calories_per_100g: 89,
    protein: 1.1,
    carbohydrates: 23.0,
    sugar: 12.0,
    fat: 0.3,
    fiber: 2.6,
    salt: 0.0,
  },
  {
    name: "Apple",
    localized: "Jablko",
    calories_per_100g: 52,
    protein: 0.3,
    carbohydrates: 14.0,
    sugar: 10.0,
    fat: 0.2,
    fiber: 2.4,
    salt: 0.0,
  },
  {
    name: "Strawberries",
    localized: "Jahody",
    calories_per_100g: 32,
    protein: 0.7,
    carbohydrates: 7.7,
    sugar: 4.9,
    fat: 0.3,
    fiber: 2.0,
    salt: 0.0,
  },
  {
    name: "Blueberries",
    localized: "Čučoriedky",
    calories_per_100g: 57,
    protein: 0.7,
    carbohydrates: 14.0,
    sugar: 10.0,
    fat: 0.3,
    fiber: 2.4,
    salt: 0.0,
  },
  {
    name: "Oranges",
    localized: "Pomaranč",
    calories_per_100g: 47,
    protein: 0.9,
    carbohydrates: 12.0,
    sugar: 9.0,
    fat: 0.1,
    fiber: 2.4,
    salt: 0.0,
  },
  {
    name: "Grapes",
    localized: "Hrozno",
    calories_per_100g: 69,
    protein: 0.7,
    carbohydrates: 18.0,
    sugar: 15.0,
    fat: 0.2,
    fiber: 0.9,
    salt: 0.0,
  },
  {
    name: "Avocado",
    localized: "Avokádo",
    calories_per_100g: 160,
    protein: 2.0,
    carbohydrates: 8.5,
    sugar: 0.7,
    fat: 15.0,
    fiber: 6.7,
    salt: 0.02,
  },
  {
    name: "Lemon",
    localized: "Citrón",
    calories_per_100g: 29,
    protein: 1.1,
    carbohydrates: 9.3,
    sugar: 2.5,
    fat: 0.3,
    fiber: 2.8,
    salt: 0.0,
  },
  {
    name: "Peach",
    localized: "Broskyňa",
    calories_per_100g: 39,
    protein: 0.9,
    carbohydrates: 9.5,
    sugar: 8.4,
    fat: 0.3,
    fiber: 1.5,
    salt: 0.0,
  },
  {
    name: "Pear",
    localized: "Hruška",
    calories_per_100g: 57,
    protein: 0.4,
    carbohydrates: 15.0,
    sugar: 10.0,
    fat: 0.1,
    fiber: 3.1,
    salt: 0.0,
  },
  {
    name: "Raspberry",
    localized: "Maliny",
    calories_per_100g: 52,
    protein: 1.2,
    carbohydrates: 12.0,
    sugar: 4.4,
    fat: 0.7,
    fiber: 6.5,
    salt: 0.0,
  },
  {
    name: "Watermelon",
    localized: "Červený melón",
    calories_per_100g: 30,
    protein: 0.6,
    carbohydrates: 8.0,
    sugar: 6.0,
    fat: 0.1,
    fiber: 0.4,
    salt: 0.0,
  },
  {
    name: "Pineapple",
    localized: "Ananás",
    calories_per_100g: 50,
    protein: 0.5,
    carbohydrates: 13.0,
    sugar: 10.0,
    fat: 0.1,
    fiber: 1.4,
    salt: 0.0,
  },
  {
    name: "Kiwi",
    localized: "Kiwi",
    calories_per_100g: 61,
    protein: 1.1,
    carbohydrates: 15.0,
    sugar: 9.0,
    fat: 0.5,
    fiber: 3.0,
    salt: 0.0,
  },
  {
    name: "Mango",
    localized: "Mango",
    calories_per_100g: 60,
    protein: 0.8,
    carbohydrates: 15.0,
    sugar: 14.0,
    fat: 0.4,
    fiber: 1.6,
    salt: 0.0,
  },
  {
    name: "Plum",
    localized: "Slivka",
    calories_per_100g: 46,
    protein: 0.7,
    carbohydrates: 11.4,
    sugar: 9.9,
    fat: 0.3,
    fiber: 1.4,
    salt: 0.0,
  },
  {
    name: "Cherry",
    localized: "Čerešne",
    calories_per_100g: 50,
    protein: 1.0,
    carbohydrates: 12.0,
    sugar: 8.0,
    fat: 0.3,
    fiber: 1.6,
    salt: 0.0,
  },
  {
    name: "Apricot",
    localized: "Marhuľa",
    calories_per_100g: 48,
    protein: 1.4,
    carbohydrates: 11.0,
    sugar: 9.0,
    fat: 0.4,
    fiber: 2.0,
    salt: 0.0,
  },
  {
    name: "Grapefruit",
    localized: "Grapefruit",
    calories_per_100g: 32,
    protein: 0.6,
    carbohydrates: 8.1,
    sugar: 7.0,
    fat: 0.1,
    fiber: 1.1,
    salt: 0.0,
  },
  {
    name: "Cantaloupe Melon",
    localized: "Mliečny melón Cantaloupe",
    calories_per_100g: 34,
    protein: 0.8,
    carbohydrates: 8.2,
    sugar: 7.9,
    fat: 0.2,
    fiber: 0.9,
    salt: 0.01,
  },

  // --- NUTS, SEEDS & OILS ---
  {
    name: "Almonds",
    localized: "Mandle",
    calories_per_100g: 579,
    protein: 21.0,
    carbohydrates: 22.0,
    sugar: 4.4,
    fat: 50.0,
    fiber: 12.0,
    salt: 0.0,
  },
  {
    name: "Walnuts",
    localized: "Vlašské orechy",
    calories_per_100g: 654,
    protein: 15.0,
    carbohydrates: 14.0,
    sugar: 2.6,
    fat: 65.0,
    fiber: 6.7,
    salt: 0.0,
  },
  {
    name: "Peanut Butter",
    localized: "Arašidové maslo",
    calories_per_100g: 588,
    protein: 25.0,
    carbohydrates: 20.0,
    sugar: 4.7,
    fat: 50.0,
    fiber: 6.0,
    salt: 0.04,
  },
  {
    name: "Olive Oil",
    localized: "Olivový olej",
    calories_per_100g: 884,
    protein: 0.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 100.0,
    fiber: 0.0,
    salt: 0.0,
  },
  {
    name: "Chia Seeds",
    localized: "Chia semienka",
    calories_per_100g: 486,
    protein: 17.0,
    carbohydrates: 42.0,
    sugar: 0.0,
    fat: 31.0,
    fiber: 34.0,
    salt: 0.04,
  },
  {
    name: "Cashews",
    localized: "Kešu orechy",
    calories_per_100g: 553,
    protein: 18.0,
    carbohydrates: 30.0,
    sugar: 5.9,
    fat: 44.0,
    fiber: 3.3,
    salt: 0.03,
  },
  {
    name: "Pumpkin Seeds",
    localized: "Tekvicové semienka",
    calories_per_100g: 559,
    protein: 30.0,
    carbohydrates: 10.7,
    sugar: 1.4,
    fat: 49.0,
    fiber: 6.0,
    salt: 0.02,
  },
  {
    name: "Sunflower Seeds",
    localized: "Slnečnicové semienka",
    calories_per_100g: 584,
    protein: 21.0,
    carbohydrates: 20.0,
    sugar: 2.6,
    fat: 51.0,
    fiber: 8.6,
    salt: 0.02,
  },
  {
    name: "Coconut Oil",
    localized: "Kokosový olej",
    calories_per_100g: 862,
    protein: 0.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 100.0,
    fiber: 0.0,
    salt: 0.0,
  },
  {
    name: "Sunflower Oil",
    localized: "Slnečnicový olej",
    calories_per_100g: 884,
    protein: 0.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 100.0,
    fiber: 0.0,
    salt: 0.0,
  },
  {
    name: "Ghee",
    localized: "Ghee maslo",
    calories_per_100g: 897,
    protein: 0.0,
    carbohydrates: 0.0,
    sugar: 0.0,
    fat: 99.5,
    fiber: 0.0,
    salt: 0.0,
  },
  {
    name: "Soy Sauce",
    localized: "Sójová omáčka",
    calories_per_100g: 53,
    protein: 8.1,
    carbohydrates: 4.1,
    sugar: 0.8,
    fat: 0.1,
    fiber: 0.8,
    salt: 14.0,
  },
  {
    name: "Almond Butter",
    localized: "Mandľové maslo",
    calories_per_100g: 614,
    protein: 21.0,
    carbohydrates: 19.0,
    sugar: 4.8,
    fat: 56.0,
    fiber: 10.0,
    salt: 0.01,
  },
  {
    name: "Sesame Seeds",
    localized: "Sezamové semienka",
    calories_per_100g: 573,
    protein: 18.0,
    carbohydrates: 23.0,
    sugar: 0.3,
    fat: 50.0,
    fiber: 12.0,
    salt: 0.03,
  },

  // --- EXTRAS ---
  {
    name: "Honey",
    localized: "Med",
    calories_per_100g: 304,
    protein: 0.3,
    carbohydrates: 82.0,
    sugar: 82.0,
    fat: 0.0,
    fiber: 0.2,
    salt: 0.01,
  },
  {
    name: "Dark Chocolate",
    localized: "Horká čokoláda",
    calories_per_100g: 598,
    protein: 7.8,
    carbohydrates: 46.0,
    sugar: 24.0,
    fat: 43.0,
    fiber: 11.0,
    salt: 0.05,
  },
  {
    name: "Ketchup",
    localized: "Kečup",
    calories_per_100g: 97,
    protein: 1.2,
    carbohydrates: 26.0,
    sugar: 22.0,
    fat: 0.1,
    fiber: 0.3,
    salt: 2.2,
  },
  {
    name: "Mustard",
    localized: "Horčica",
    calories_per_100g: 66,
    protein: 4.4,
    carbohydrates: 6.4,
    sugar: 3.0,
    fat: 4.0,
    fiber: 3.3,
    salt: 2.8,
  },
  {
    name: "Mayonnaise",
    localized: "Majonéza",
    calories_per_100g: 680,
    protein: 1.0,
    carbohydrates: 0.6,
    sugar: 0.6,
    fat: 75.0,
    fiber: 0.0,
    salt: 1.2,
  },
  {
    name: "Maple Syrup",
    localized: "Javorový sirup",
    calories_per_100g: 260,
    protein: 0.0,
    carbohydrates: 67.0,
    sugar: 60.0,
    fat: 0.1,
    fiber: 0.0,
    salt: 0.01,
  },
];

const run = async () => {
  const client = new MongoClient(MONGODB_URI);

  try {
    console.log("Connecting to MongoDB...");
    await client.connect();
    const db = client.db(DB_NAME);
    const collection = db.collection(FOOD_COLLECTION);

    console.log("Connected successfully.");
    console.log(`Preparing to seed ${foodData.length} food items...`);

    // Prepare operations for the native driver
    const bulkOps = foodData.map((item) => {
      // Build standard JS object for translations
      const localizedNames: Record<string, string> = {};
      if (item.localized) {
        localizedNames["sk"] = item.localized;
      }

      return {
        updateOne: {
          filter: { name: item.name },
          update: {
            $set: {
              name: item.name,
              localizedNames: localizedNames,
              calories_per_100g: item.calories_per_100g,
              fat: item.fat,
              protein: item.protein,
              sugar: item.sugar,
              carbohydrates: item.carbohydrates,
              fiber: item.fiber,
              salt: item.salt,
              updatedAt: new Date(),
            },
            $setOnInsert: {
              createdAt: new Date(),
            },
          },
          upsert: true,
        },
      };
    });

    const result = await collection.bulkWrite(bulkOps);

    console.log("Seeding complete!");
    console.log(
      `Added: ${result.upsertedCount}, Updated: ${result.modifiedCount}`,
    );
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    await client.close();
    console.log("Disconnected from MongoDB.");
  }
};

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
